services:
  redis:
    container_name: covid-api-redis-test
    volumes:
      - redis-data-test:/data
  app:
    command: ["npm", "test"]
    build: .
    environment:
      - TEST_MODE=true
      - DOCKER=true
    container_name: covid-api-app-test

volumes:
  redis-data-test:
